### ISSUE TITLE
Conditional receiveFrom

### ISSUE THREAD

**Issue by barticus** [reflectiveSingleton/footwork#2]
When adding a .receiveFrom to an observable, you should be able to add a condition to it, so it only syncs the value if the condition is truthy. 

E.g. (to use the to do app example) you might have the Todo item component repeating for each todo item (lets say items 1-10), and an edit item component. When the edit item component submits (let's say item 6 was updated), it publishes the updated item, but you only want the Todo item component for item 6 to sync up. 

Ideal implementation:
self.item = fw.observable().receiveFrom('ItemEditor', 'UpdatedItem').when(function(item){return item.Id() ==self.item.Id()}) 

(original discussion: https://groups.google.com/forum/#!topic/knockoutjs/yUmu_xQ9A5g)

**Comment by reflectiveSingleton** [comment]
This feature has been created in commit: 43852a5e280f20b5f627687ad3c2c3840bef47d0

Also went ahead and added tests around it as well. Thanks for the suggestion!
